{% set version = "2.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-stopwords
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/stopwords_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/stopwords/stopwords_{{ version }}.tar.gz
  sha256: b66bccc786200c6ec600be8340e2801bbc7ee787fa5c5a15bc201306861706b9

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-isocodes
    - r-usethis
    - r-desc
  run:
    - r-base
    - r-isocodes
    - r-usethis
    - r-desc

test:
  commands:
    - $R -e "library('stopwords')"           # [not win]
    - "\"%R%\" -e \"library('stopwords')\""  # [win]

about:
  home: https://github.com/davnn/stopwords
  license: MIT
  license_file: LICENSE
  summary: Provides multiple sources of stopwords, for use in text analysis and natural language processing.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - stevierene82
