{% set version = "1.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-stopwords
  version: {{ version|replace("-", "_") }}

source:
  fn: stopwords_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/stopwords_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/stopwords/stopwords_{{ version }}.tar.gz
  sha256: 9b727a5d827ac8dcfa6329140d294dcf964a06d80132b4ca434330d0ee02b1da

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-isocodes
  run:
    - r-base
    - r-isocodes

test:
  commands:
    - $R -e "library('stopwords')"           # [not win]
    - "\"%R%\" -e \"library('stopwords')\""  # [win]

about:
  home: https://github.com/davnn/stopwords
  license: MIT
  summary: Provides multiple sources of stopwords, for use in text analysis and natural language
    processing.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
    - stevierene82
